server.port=7000
# ssl configuration for HTTPS add false for local testing or https://localhost:7000
server.ssl.enabled=true
server.ssl.key-store=/var/tmp/appcerts/pguatkey.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=pguat5916
server.ssl.key-alias=pguat

spring.application.name=netbanking-simulator

#Uat DB connection details replace with your own DB connection details
spring.datasource.url=jdbc:oracle:thin:@172.32.18.99:1521/XEPDB1
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=pgiuat
spring.datasource.password=pgiuat

spring.datasource.hikari.pool-name=NetbankingSimulatorPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false

#Checksum key for HRE simulator.
simulator.hre.checksum-key=bduat@axis

simulator.delay.default-seconds=5
simulator.delay.max-seconds=120
simulator.duplicate.second-call-delay-ms=1500
